### ISSUE TITLE
Suggestions for labs

### ISSUE THREAD

**Issue by MansMeg** [STIMALiU/BayesLearnCourse#3]
- Make the labs more self-contained (or more explicit)
The students are having a hard time finding exact what for example $\tau^2_n$ means in the lecture slides. Maybe specify either everything in the lab or more information on where the different parts needed can be found in the slides?

- There is some confusion in the difference between starting state in the MCMC chain and the prior. Maybe create an explicit task to change the initial state to study how the chain "burn in" to the region of high posterior density.

- There are a lot of different problems with small problems/bugs. 
Maybe add a little more explicit task on how to implement a Gibbs sampler for an example where we create tests to check the different sampler with a test suite they can access through markmyassignment. Then they can check the different parts better

- There are some that are having problems in understanding the conditional posterior of parameters. Maybe we should add a task of deriving a Gibbs sampler step as a part of the lab?

- In lab 2: The probit model should is said to be found in Lecture 8, but it is found in Lecture 7?

- Should they present their code? Should we suggest to use R-markdown? I could write a template to use so that it is easier correct the lab?

- Maybe add stan or JAGS to the labs to compare the results (instead of using glm). That would make them understand how to specify a model and prior more explicit.

- Wrtie down a checklist on how to correct lab reports. Now I forgot to comment all lab reports in the beginning.

**Comment by psiden** [comment]
Many of these bullets have been taken care of by the recent changes to Lab 3. Bullet 2 and 3 will be more clearly mentioned in the lectures.
