### ISSUE TITLE
Exam improvements

### ISSUE THREAD

**Issue by mattiasvillani** [STIMALiU/BayesLearnCourse#6]
- Explain in the exam documentation how to read files from given_files. Explain that the student needs to set the path in R or copy to student_tilde.
- Explain how to print a figure that can then be pasted into LibreOffice. Suggest:
 png(‘myPlot.png’);plot(rnorm(4));dev.off()

**Comment by MansMeg** [comment]
One problem with the current exam was that not all student showed their code. Maybe give them an RMarkdown exam template?
